name = "jasonbyday"
compatibility_date = "2025-03-24"

[env]
production = { }

[build]
command = "npm run build"
pages_build_output_dir = "dist"

[build.upload_environment_variables]
CF_PAGES_BRANCH = "CF_PAGES_BRANCH"
CF_PAGES_URL = "CF_PAGES_URL"

[build.environment_variables]
MYSITE_URL = { binding = "vars", value = "https://jasonbyday.com", if = { equals = "main" }  } # Override for production

[build.environment_variables.MYSITE_URL.rules]
CF_PAGES_BRANCH = { value = "$CF_PAGES_URL", if = { not = { equals = "main" } } } # Default to preview